### ISSUE TITLE
No StreetPass hits 

### ISSUE THREAD

**Issue by ghost** [taintedzodiac/relaymyhome#19]
Hello,
I have configured relaymyhome following GBATemp steps - using Ethernet and WiFi to create Nintendo Zone named NZ@McD1. I ran the relaymyhome script from terminal, connected 3DSXL to the hotspot, Nintendo Zone icon appeared on 3DSXL, got a little prompts saying that Nintendo Zone service is available. Upon opening it I even managed to get Pokemon ORAS screen with information that the content is not translated to my language, so it appears that there is a connection.
The problem is that I don't recieve any StreetPass hits, even though i rebooted computer several times, restarted both the 3DSXL and the connection many times, tried changing MAC address to 4e:53:50:4f:4f:43 before even running the script, checked with grep command if it really changed - it did, but still nothing. Upon opening Web Browser on 3DSXL I get error 003-3305 and cannot browse the Web. I crave for help, as I tried everything that I found possible and nothing helped.
I would appreciate all given help.

3DSXL is running software Ver. 9.4.0-21E
Using Mid-2011 21,5" iMac, 10.9.4

**Comment by Jeraimee** [comment]
Same here, no streetpass.

**Comment by Jeraimee** [comment]
Yea, sharing is on and the wired connection was fine. Tried both NZ@McD1 (case the same) and attwifi. Ran a couple passes on "full" and got nada. Tried at the office (wired network has a somewhat restrictive firewall blocking some outbound ports) and at home with all outbound ports allowed (also verified no fw was active on the Mac).

**Comment by Jeraimee** [comment]
So I've now got passes working. Still no Nintendo Zone but passes are working. I configured the Wifi SSID (NZ@McD1) and then added the wireless network to the DS. The connection test fails so you have to add DNS servers to the connection manually (8.8.8.8, 8.8.4.4) then test again - it'll pass.
Now passes work as intended.
It looks like the Wifi sharing isn't handing out routing/dns info like it's supposed to. I'll continue to research.

**Comment by taintedzodiac** [comment]
> It looks like the Wifi sharing isn't handing out routing/dns info like it's supposed to.

That does make a lot of sense. Good find!

**Comment by MiNGiEs** [comment]
I could get both my Nintendo zone, and my internet browser on my DS to work, and ran the script on my laptop but still no hits.

**Comment by phantom42** [comment]
Having the same issues with no passes. OSX 10.10.1 on my iMac - Internet sharing is on, no security, default channel (11), and I've tried both network names. Everything is updated on my 3DSXL, turned off my main net connection and have it connected to the shared internet (having tried both auto dns and the google dns as suggested). The Nintendo Zone shows up if I'm connected to NZ@McD1, but not attwifi. The internet works on the 3DSXL on either connection. I get no streetpass hits, though.

So I did a little experimentation and I ran into and found the same issues I had when I was on Lion, when I forked this for similar problems.

Attempting to manually run the command to change the mac address isn't working. On Lion, this would fail if Internet Sharing was on, so I'd disable that (which I can no longer figure out how to do via command line in Yosemite)  before setting the mac address. But here, it doesn't seem to work at all. I've tried both with Internet sharing on and off, and there is no change in either case.

**Comment by SoSu28** [comment]
I will report the same issue on Yosemite that MiNGiEs and phantom42 have. I  can see the Nintendo Zone and pass the Internet connection test. The script runs fine, but I do not receive any streetpass hits.

**Comment by taintedzodiac** [comment]
For those still experiencing issues: have you tried creating a new administrator account and seeing if you're able to run the script under that account? Perhaps it's a matter of permissions more than the machine/OS configuration.

**Comment by phantom42** [comment]
I actually just reinstalled the whole OS over the weekend, obliterating everything on my HD. I grabbed a fresh copy of relaymyhome, chmod'ed it, and ran it. Still no luck. I also tried manually spoofing the mac address again, also with no luck.

**Comment by MuzzMoo** [comment]
Hello World,

I have been trying without much success - Create the zone - run the script. NZ@McD1 SSID 

2DS (9.5) shows the Nintendo Zone but never get any street pass hits.

Script does not report any errors - Triedd attwifi and _The Cloud

Would be nice to get it up and running.

Happy gaming,

Dave

**Comment by Gorczyk** [comment]
Hi guys, it OP here, guessGitHub wiped my account (I didn't confirm email or sth)
So here's a funny case, some bad and some good news:
I sold my 3DS XL without doing a system transfer (yeah, dumb of me, but I didn't want to wait, because the prices were dropping fast) and got a New 3DS XL yesterday and connected it to "homepass realy" (or at least wanna-be-homepass relay) and guess what? I get Streetpass hits from my PREVIOUS console! It means that some data has been left here in the homepass relay, so it's kinda working as a regular relay.
The downside is even tough I added DNS servers just as Jeraimee suggested, I still get no hits.
Got a few ideas: What regions are your consoles set to? Mine is set to Poland where there's no streetpass relays at all, the same goes for my current residence (and IP address also). I'll try with some kind of proxies, changing regions on console etc and I'll let you know.

**Comment by phantom42** [comment]
I'm in the US and my console is set to the same.

**Comment by Mishulo** [comment]
I'm on the same boat - used to work a few months ago, now although the script seems to run fine, I have no streetpasses and I can't get past the "service unavailable in your region" Nintendo Zone screen. I've tried using NZ@McD1 and attwifi, from an iMac and a Macbook Air, both running Yosemite, with both "standard" and Google DNS. Console is set to Italian.

**Comment by Gorczyk** [comment]
Hi there, got some bad news.
I tracked the problem down (at least in my case). In the act of despair I started to set homepass relay on Windows 7 Bootcamp, first thing there is to run a maccheck.cmd command to see if installed wifi card is able to spoof MAC address, and guess what? It is not (the tool produced a line of zeroes, which means it can't change MAC address). I just turned wifi tethering on (on OS X), and without spoofing the MAC address waited a minute for my streetpass, and guess what? I still got the hit from my previous console. It seems that spoofing doesn't work, I'll try to confirm this with some other devices/software, but guess the problem is buried in MAC addresses not changing.

**Comment by taintedzodiac** [comment]
@Gorczyk That would explain the issues. Could you provide the model of your WiFi chipset so others can compare?

**Comment by Gorczyk** [comment]
@taintedzodiac 
I've got mid 2011 21,5" iMac i5 with Atheros AR938x Wireless Network Adapter(according to Windows device menager) /Atheros AR9388-AL1A 802.11n (according to ifixit.com). 
Something I figured out - the problem is probably the wireless adapter itself:
phantom42, MuzzMoo and me have iMacs and the homepass relay doesn't work
Jeraimee and SoSu28 have Macbooks and it works for them.
According to ifixit.com Macbooks have Broadcom wireless adapter with Skyworks front-end modules. It seems that the difference lies in wireless adapters, therefore eg. SoSu28 was able to set relay on Macbook, not iMac even though he did exactly the same steps on both of them. Another thing is that Windows guides on relays say that spoofing MAC address on Atheros cards may end up with a BSOD.

**Comment by phantom42** [comment]
@Gorczyk This is interesting as until I upgraded to Yosemite, I *could* spoof the address.

**Comment by Gorczyk** [comment]
BLOODY HELL SOMETHING HAPPENED AND IT WORKS!
I used MacDaddyX to spoof my MAC yesterday night, today morning (to my suprise) I didn't get the usual streetpass hit, but came back home, turned the relay back on and got 6 hits from people around the world! I surely didn't pass them by on street, as I checked it on my way home, so it must be it!
http://imgur.com/nV7Ibjg

**Comment by taintedzodiac** [comment]
@Gorczyk Any further luck using that method? My first thought was that if it wasn't actually working still, you might have passed by a McDonalds or a Starbucks at some point (although I certainly hope it's not the case).

**Comment by phantom42** [comment]
I tried the same process as @Gorczyk - installed MacDaddyX and tried spoofing the address. I just kept getting failure messages, so I gave up and tried the RelayMyHome. Miraculously I got 4 streetpasses!

So I tried running the script again - nothing. Tried a few more times after waiting a day  nothing.

I tried recreating the same steps with MacDaddyX - still kept getting failures and no Streetpasses with RelayMyHome.

Eventually, I was able to get a success message when spoofing with MacDaddyX, but still no more Streetpasses for me.

**Comment by Gorczyk** [comment]
Hi,
sorry for late response, but I assumed no one was interested in the issue anymore, as I got no response to last post.
Relay on Macintosh is possible, I used MacDaddyX to spoof MAC address to 4e:53:50:4f:4f:46 and get 6 streetpass hits every 8 hours (even if I change the MAC to another, I still have to wait for 8 hours, don't know why). 

I got MacDaddyX, installed it, selected en1 adapter, set rest to: http://imgur.com/3gFjCK2 and hit change. App asked me for admin password, I typed it in and got a message for succesful MAC change.

@taintedzodiac I didn't pass any McD or Starbuck's as there are no streetpass relays in my country at all.
@phantom42, the message you got was probably something like "it didn't like the MAC change", I also got it a few times, just select adapter manufacturer to proper one or leave it for "none", it depends on I don't even know what, you just need luck.

I'd be more than happy to provide you with more info if you need it.

**Comment by taintedzodiac** [comment]
So based on what @Gorczyk has found, it seems like there might be a different way that these specific chipsets need to be commanded to change their MAC addresses. That's the conclusion I'm coming to.

**Comment by Gorczyk** [comment]
@taintedzodiac Well, it looks like, but the most interesting part is why I still have 8h cooldown, even if I spoof to another MAC/reboot/disconnect/create new sharing  etc.It seems that another user had the same problem but it's still unresolved.

**Comment by Gorczyk** [comment]
Well hello again,
I've managed to run the script on a different Mac. It was early 2009 24" iMac running OSX 10.8, and everything was as smooth as possible, spoofing, cycling worked just as it was supposed to, not only once, but on a daily basis, providing lots of Streetpass hits. Nothing new actually, but we may create a list of supported Macs just for the reference, so people know right away that script would work for them.

**Comment by alexdarke** [comment]
Has there been a firm confirmation of what versions of Mac OSX this script works on and which ones it does not?

**Comment by taintedzodiac** [comment]
@alexdarke I haven't tried it on El Capitan yet, personally. The common problem has been a combination of some chipsets not being supported, and some versions of the OS being problematic.

**Comment by alexdarke** [comment]
Hmmm. But it IS actively working for folks. I wondered as this thread was around the same time as the last updates to the files, so wanted to confirm. It has to be the firewall. I guess I'll find out tonight. Thank you for the information.

**Comment by alexdarke** [comment]
Just for the record, it was the firewall. Great script. Makes this much easier. Appreciate it!

**Comment by taintedzodiac** [comment]
Great. Thanks for following up!
